### PR TITLE
Auto-delete branches on PR merge

### PR DESCRIPTION
**Pull request by samuelallan72**
As far as I know, we never have cases where we want to keep the branch after a PR has merged.
And if we do on a rare occasion,
it should be easy to restore the branch.

Auto-deleting brings some conveniences,
including more efficiency and less forgotten stale branches.

Fixes: #106

### CODE REVIEW

**Comment by Pjack** [comment]
Initial a conversation to gather feedback from the team. 
If no concerns are raised within a couple of days, we can proceed with merging.

**Review by Pjack — COMMENTED** [review]
Initial a conversation to gather feedback from the team. 
If no concerns are raised within a couple of days, we can proceed with merging.

**Review by Pjack — CHANGES_REQUESTED** [review]
Initial a conversation to gather feedback from the team. 
If no concerns are raised within a couple of days, we can proceed with merging.

**Review by Pjack — COMMENTED** [review]
Initial a conversation to gather feedback from the team. 
If no concerns are raised within a couple of days, we can proceed with merging.

**Review by chanchiwai-ray — APPROVED** [review]

**Review by jneo8 — APPROVED** [review]

**Review by gabrielcocenza — APPROVED** [review]
I don't see downsides on deleting the branch. LGTM

**Review by Pjack — APPROVED** [review]

**Pull request merged**
