### PR TITLE
Manage jira_sync_config.yaml

### PR DESCRIPTION
**Pull request by chanchiwai-ray**
Manage `jira_sync_config.yaml` for the rest of the projects (exception: only apply to snap_tempest main branch)

### CODE REVIEW

**Comment by samuelallan72** [comment]
Thanks @chanchiwai-ray ! While you're here, to reduce the number of automated PRs, could you set `add_gh_comment` to true?

**Comment by chanchiwai-ray** [comment]
> Thanks @chanchiwai-ray ! While you're here, to reduce the number of automated PRs, could you set `add_gh_comment` to true?

Thanks, I actually did not know that was set to `false`

**Review by Pjack — CHANGES_REQUESTED** [review]
How about .jira_sync_config.yaml in this repository ?

https://github.com/canonical/solutions-engineering-automation/blob/main/.github/.jira_sync_config.yaml

**Comment by Pjack** [comment]
I also create another issue: https://github.com/canonical/solutions-engineering-automation/issues/102 to manage the hierachy of terraform variable.

**Comment by chanchiwai-ray** [comment]
> How about .jira_sync_config.yaml in this repository ? https://github.com/canonical/solutions-engineering-automation/blob/main/.github/.jira_sync_config.yaml

it's there

**Review by samuelallan72 — APPROVED** [review]

**Review by Pjack — APPROVED** [review]

**Pull request merged**
