### PR TITLE
Smart summarise weekly test results

### PR DESCRIPTION
**Pull request by samuelallan72**
Move the message building to a python script to make it easier
to customise the message,
and add some features:

- only notify `@soleng` if there were failed tests
- print a quick summary of number of failed tests

Fixes: #6
Fixes: #5

### CODE REVIEW

**Comment by samuelallan72** [comment]
Note: untested in the workflow

**Review by Pjack — APPROVED** [review]

**Comment by samuelallan72** [comment]
I tested this in a test organisation and fixed an issue writing the summary results to the github_env.  Also rebased on main.  Ready for review. :D

**Review by jneo8 — APPROVED** [review]
Thanks, LGTM

**Comment by samuelallan72** [comment]
I realised I can launch a workflow from another branch, so I've started https://github.com/canonical/solutions-engineering-automation/actions/runs/10190041941 from this branch for full e2e testing.

**Review by chanchiwai-ray — APPROVED** [review]

**Pull request merged**
